language: node_js
node_js:
  - 17
services:
  - xvfb
script: 
  - xvfb-run npm test
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  bucket: "serverless-unsj"
  acl: public_read
