language: ruby
cache: bundler
rvm:
- 2.3.1
branches:
  only:
  - master
before_install:
- sudo gem install bundler
- sudo apt-get -qq update
- sudo pip3 install awscli
script:
- sudo bundle exec jekyll build
deploy:
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  bucket: serverless-unsj
  acl: public_read